### ISSUE TITLE
R1: major issue 1, lack of awareness

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#17]
>Let me begin by first clarifying my own positionality with regard to the subject at hand: I am an enthusiastic supporter of open science practices in linguistics, and have been for many years. So in this sense, I am solidly in favor of more exhortations in print to our colleagues to improve their practices, and recognize that many linguists are not trained in these practices and left to more or less fend for themselves. This is a sad state of affairs for our field and others, and needs to be corrected through outreach and education.
>
>This paper, however, seems to me to be quite weak on two fronts. The first is what seems to be a concerning lack of awareness of recent work in linguistics to promote open science, especially with regard to research data. Of particular note is the absence of two fairly recent references in linguistics. The first is a highly-cited, multi-authored position paper calling for reproducible linguistics research that was published in this very journal in 2018:
>
>Berez-Kroeker, Andrea L., Lauren Gawne, Susan Kung, Barbara F. Kelly, Tyler Heston, Gary Holton, Peter Pulsifer, David Beaver, Shobhana Chelliah, Stanley Dubinsky, Richard P. Meier, Nicholas Thieberger, Keren Rice & Anthony Woodbury. 2018. Reproducible research in linguistics: A position statement on data citation and attribution in our field. Linguistics 56(1): 1–18. https://doi.org/10.1515/ling-2017-0032.
>
>The second is an open access handbook from the very prominent MIT Press Open, with 56 chapters on open data management from more than 100 international authors across many subfields (which I refer to later in this review as OHLDM):
>
>Berez-Kroeker, Andrea L., Bradley McDonnell, Eve Koller & Lauren B. Collister (eds.). 2022. The open handbook of linguistic data management. Cambridge, MA: MIT Press Open. https://doi.org/10.7551/mitpress/12200.001.0001.
>
>And then of course there is the 2021 statement from the Linguistic Society of America on the Scholarly Merit of Open Scholarship in Linguistics:
https://www.linguisticsociety.org/content/statement-scholarly-merit-and-evaluation-open- scholarship-linguistics.
>
>It seems to me that the authors have not done their due diligence in terms of understanding the state of literature in the field, especially in light of their claims that there is no such literature.
>
> That is the first major weakness of this paper. Misrepresenting the current state of the field makes it very easy for readers to dismiss the topic altogether. Papers urging the research culture of the entire field forward need to carefully and accurately describe the problem at hand, so that readers can recognize the problem for what it is. This is turn makes it harder for readers to ignore the problem, and encourages them to think carefully about how they can help solve it in their own work. My own review is a case in point: I don’t recognize the world of linguistics as described in this paper -- that is, one in which no linguists have really thought seriously about this issue before today – and I am writing a negative review despite the fact that I hold this topic dear.

TODO

- [x] add suggested refs to bib file
- [x] reread manuscript and find appropriate places to include refs
- [x] In response letter, refer to this entire comment ("We thank the reviewer for blah blah..."

**Comment by mfeliuribas** [comment]
**Introduction:**
- Paragraph 1, p.3: I would "attenuate" this claim ("Though it may come as a surprise to some, these open, transparent research practices have not been the norm in empirical and quantitative sciences") by recognizing that some efforts have, indeed, been made, particularly in relation to research data. We could cite [Berez-Kroeker et al. (2018)](https://www.degruyter.com/document/doi/10.1515/ling-2017-0032/html) and [Berez-Kroeker et al. (2022)](https://direct.mit.edu/books/oa-edited-volume/5244/The-Open-Handbook-of-Linguistic-Data-Management)
- Paragraph 2, p. 3: "To properly contextualize the need for open science, one must first consider the so-called
reproducibility (replication) crisis. ([Zwaan et al., 2018](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/making-replication-mainstream/2E3D8805BF34927A76B963C7BBE36AC7))"
- Paragraph 2, p. 4: "[...] and have led to periods of introspection and self-reflection in many adjacent fields, among them, linguistics (e.g., Berez-Kroeker et al., 2018)."
- Paragraph 4, p. 4: 
> - Reviewer 1 seemed very upset because some citations (about efforts made within linguistics to foster open science) were missing. 
> - I think that it would be a good idea if we relate the aim of our paper to these initial efforts (I am pretty sure that reviewer 1 would be more positive then!). 
> - In the beginning of this paragraph ("The present work intends to help make open science practices understandable and accessible...") (or elsewhere), we could add something like "Some researchers have called for action to make linguistics a more transparent, reproducible science (e.g., Berez-Kroeker et al., 2018; Berez-Kroeker et al., 2022). The aim of our paper is to support researchers in doing so". 
> > - Maybe not with these exact words, but this would be a way of recognizing the work of other people that are also committed to open science in linguistics!

**Comment by mfeliuribas** [comment]
**Open Data:**
- Berez-Kroeker, McDonell, Collister & Koller (2021) (in Berez-Kroeker et al., 2021) describe data as "the lifeblood of research" (p. 3). Maybe we could reference this metaphor. 
- Not all linguists collect their own data and some use available corpora. This topic is widely discussed in Berez-Kroeker et al. (2018) (also a main topic in Berez-Kroeker et al., 2021). If we consider it necessary, maybe we could add something related to that, for example, the importance of not only sharing our data, but also of citing others properly (e.g., when we use a specific corpus). For what I have read, most of the efforts in linguistics concern data management and data citation. 
- Paragraph 2, p. 9: It might be implicit in the last sentence of this paragraph that open data favor the accuracy of linguistic theories, but we could consider making it explicit, e.g., by adding something like "and helps develop more accurate generalizations and theories". This is actually one of the central ideas in Berez-Kroeker et al. (2021).
- Paragraph 4, p. 11: After providing different options for sharing data and after citing Quintana (2020), we could quote the European Commission, as they claim that data should be "as open as possible, as closed as necessary" ([H2020 Programme 2016](http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-data-mgt_en.pdf)). Or we could put it elsewhere. 
- Paragraph 6, p. 11: Perhaps this sentence "Linguistics, in general, does not engage in open science practices (Bochynska et al., 2023), including sharing data" could be refined? According to a couple of studies, "different subfields do have strengths in facets of research transparency [...] Practitioners in different subfields ‘do transparency’ differently, and these practices could serve as models for an eventual amalgamated standard." (Berez-Kroeker et al., 2018, p. 9). The sentence in our paper sounds too categorical, and that might be one of the issues that reviewer 1 had with it.

**Comment by mfeliuribas** [comment]
**Pre-prints:**
- Paragraph 1, p. 19-20: "The adoption of pre-prints has been slower in some fields, such as the social sciences and humanities, but this is changing as more researchers become aware of the benefits of open science, and new national and regional platforms by open science advocates continue to emerge (Gawne & Styles, 2021)." It is a chapter in Berez-Kroeker et al. (2022).
- Paragraph 4, p. 20: "Publication bias occurs when positive results are more likely to be published than negative results ([Matosin et al., 2014](https://pmc.ncbi.nlm.nih.gov/articles/PMC3917235/))."

**Comment by mfeliuribas** [comment]
**Refs ready to add to bib file (BibTex)**

@article{berez-kroeker2018,
  title={Reproducible research in linguistics: A position statement on data citation and attribution in our field},
  author={Berez-Kroeker, Andrea L and Gawne, Lauren and Kung, Susan Smythe and Kelly, Barbara F and Heston, Tyler and Holton, Gary and Pulsifer, Peter and Beaver, David I and Chelliah, Shobhana and Dubinsky, Stanley and Meier, Richard P and Thieberger, Nick and Rice, Keren and Woodbury, Anthony C},
  year={2018},
  journal={Linguistics},
  volume={56},
  number={1},
  pages={1--18},  
  publisher = "De Gruyter Mouton",
  url={osf.io/preprints/psyarxiv/ak6jr},
  DOI={10.31234/osf.io/ak6jr},
}

**Comment by jvcasillas** [comment]
Refs added to bib file via https://github.com/RAP-group/guide_to_open_science/commit/d02d7d34d20dfc19121ccaef45a6fd1ea1da91b5

Other changes still pending

**Comment by jvcasillas** [comment]
Completed via https://github.com/RAP-group/guide_to_open_science/commit/270c3068f57c079c2808462dfe2071560683c4e2
