### ISSUE TITLE
R2: intro, rephrase reference to new techniques

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#22]
> - “It necessitates that researchers implement new techniques with limited pedagogical
resources and embrace alternative methods of disseminating their research, all of which constitutes a steep learning curve.”
--> Does it always, though? For instance, in the field of language typology, there are a number of qualitative studies that are based on a sample and annotations using reference grammars. Those studies do not include any code, making them transparent simply means providing a spreadsheet with the languages and the respective annotations and sources that the authors should have in some form anyway. Can we really speak of “innnovative methodologies”?All this goes to say that, yes, some formats (e.g. using OSF) may involve a learning curve, but this is not necessarily so. It may also be about vulnerability, i.e. making all details of the study and analysis public and thus subject to potential criticism, wheareas before, those could be left partially “hidden” and “proctected”. I suggest that the authors sightly rephrase this paragraph.

TODO

- [x] brainstorm ideas for "slightly rephrasing"
- [x] how we respond to R2 will be more important than actual change

**Comment by IvanAndreuRascon** [comment]
It necessitates that researchers implement new techniques with limited pedagogical
resources and embrace alternative methods of disseminating their research, all of which constitutes a steep learning curve. However, the challenges of increasing transparency are field-specific and vary accordingly.  In some disciplines, it may simply involve sharing existing materials without the need for innovative methodologies.

_We appreciate the reviewer’s thoughtful feedback. (hehe) We agree that the challenges associated with increasing transparency vary across different fields and methodologies. In response, we have rephrased the paragraph to acknowledge that while some researchers may face a learning curve or feelings of vulnerability when adopting new transparency practices, this is not universally the case. Our revised paragraph now reads:_

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/8f9b34ac47afe6a9ab00050ed45fefef231670f5
