### ISSUE TITLE
R2: intro, rephrase "we identify 3 areas..."

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#23]
> - “To this end, we identify three areas, stance, workflow, and dissemination, in which linguists can engage in open science.”
--> rephrase: “... we identify the following three areas of stance, workflow and dissemination, ...

TODO

- [x] make change in revised doc

**Comment by IvanAndreuRascon** [comment]
To this end, we identify the following three areas—stance, workflow, and dissemination—in which linguists can engage in open science.

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/f92bdb59bb8d5bdf2ae387fe1d7bc5977fc1337e
