### ISSUE TITLE
R2: positionality statements, 

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#25]
> - Could you give a concrete example of a positionality statement early on? A concrete example is valuable to make this more understandable for researchers not familiar with this practice.

TODO 

- [x] examine to see where example can be given earlier in section
- [x] make change in qmd file

**Comment by mfeliuribas** [comment]
Although I haven't seen this in any paper I have recently read, at NWAV a couple of presenters included their positionality statements before talking about their study. I am not sure if that might help, but I took a couple of photos just in case!

**Comment by jvcasillas** [comment]
Idea: find proceedings from recent ling conference and see how many have positionality statements

**Comment by jvcasillas** [comment]
Reorganized in https://github.com/RAP-group/guide_to_open_science/pull/64
