### ISSUE TITLE
R2: positionality statements, application in linguistics

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#26]
> - “Moreover, Bucholtz et al. (2023) note that considering a researcher’s positionality may be especially important in linguistics, “[...] which relies on racially minoritized communities as sources of data yet lack adequate (if any) representation of those communities among faculty researchers” (p. 2).”
--> Does this quote really apply to linguistics in general? I can see how it is very relevant for certain areas of linguistics, but there is much linguistic research on major languages, where this point does not seem to apply. Please rephrase / explain.

TODO

- [x] hedge even more "may be"?
- [x] It seems like R2's issue is with the content of the quote, in which case I don't think any action is necessary

**Comment by RobertEspo** [comment]
If more hedging is desired:

“Moreover, Bucholtz et al. (2023) note that considering a researcher’s positionality may be especially important in linguistic research on certain language communities, such as indigenous communities, “[...] which relies on racially minoritized communities as sources of data yet lack adequate (if any) representation of those communities among faculty researchers” (p. 2).”

**Comment by jvcasillas** [comment]
I say we go with @RobertEspo suggestion for now and see how they respond.

**Comment by jvcasillas** [comment]
Included via https://github.com/RAP-group/guide_to_open_science/commit/a3531b68466cfb74fc4f53e3c4dad5d66eb0dcc4
