### ISSUE TITLE
R2: positionality statements, ex of conflict of interest

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#28]
> - “Bochynska et al. (2023) surveyed open and transparent practices in linguistics and found that only 10% of the articles sampled included statements of conflict of interest, and, among those 10%, none declared any conflicts (See also Cristea & Ioannidis, 2018; Hardwicke et al., 2022, 2020).”
--> Out of curiosity, can you give an example of a statement of conflict of interest from linguistics? Again, concrete examples would help readers less aware of / familiar with these issues understand what those statements can look like.

TODO

- [x] find/provide example
- [x] add to supplementary materials?

**Comment by RobertEspo** [comment]
I wasn't able to find any COIs just by searching, but maybe we can include something about funding? https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/neurobiology-of-simultaneous-interpreting-where-extreme-language-control-and-cognitive-control-intersect/B773BCC418A089294B5FFB26F7DBA26A This is funded by an organization, but there's no Conflict of Interest statement. Calling that out seems like it's not the move, but maybe we can add something like:

For example, if a study is funded by a grant, an ideal conflict of interest would include that information.

**Comment by jvcasillas** [comment]
COmpeting interests sections here: https://escholarship.org/uc/item/6m62j7p6#main

**Comment by jvcasillas** [comment]
Definitions and example: https://osf.io/ehyx3

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/cc905353b79d3d4b239c42c3c2d180d3ac897bdf
