### ISSUE TITLE
R2: open data, "rephrase", "clarify"

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#33]
> - “Recent efforts have attempted to encourage researchers to make linguistic data open and accessible via servers (e.g., the IRIS database).”
--> Given the goal of this paper, please add more explanation about the IRIS database here.

TODO

- [x] add one liner about IRIS

> - “open science bagdes” --> Can you explain briefly what this is?

TODO

- [x] briefly describe (like trophies for articles)

**Comment by ecorregidor** [comment]
“Recent efforts have attempted to encourage researchers to make linguistic data open and accessible via servers. A great example is the IRIS database, a language sciences digital repository freely accessible with an up- and downloadable collection of research instruments and materials. This project aligns with the Open Science Badges offered in some journals  (e.g., Language Learning, Language and Speech). Researchers earn these Open Science badges by making digitally shareable and publicly available different items of their research (data, analytic code, materials, papers, and supplements, among others). In other cases, journals have made data sharing a requirement for publication (e.g., Applied Psycholinguistics)."

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/ae710f0ce803966cde9a517bfa65e518ca85f231
