### ISSUE TITLE
R2: open data, elaborate on why people hesitate to share data

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#34]
> - “Though researchers may understandably hesitate to share their data, we believe
understanding the benefits of open data can help alleviate any concerns.”
--> This point needs to be elaborated more in that there may be very different motivations for preferring not to share data. Corpus data may contain sensitive personal information (e.g. video, audio) and speakers may not consent to making it public. Authors of the study may not have the rights to publish the data that their study is based. In this case, it may be possible to make processed data publicly available, but not the raw data (i.e. data can mean different things, and should be distinguished in more detail here). In other cases, it may simply be the fear of making all data and annotation choices criticiseable by making everything publicly available. Those are very different perspectives that call for very different solutions / approaches. This needs to be discussed and differentiated in more detail.

TODO

- [x] explain why people in different areas may not want to or be able to share data
- [x] give examples from a few areas (also, check and make sure this isn't already addressed later on in manuscript)

**Comment by RobertEspo** [comment]
Addressed two paragraphs down, starting in this paragraph: "Having stated all the above, it is necessary to recognize that the field of linguistics faces unique challenges with regard to open data."

> Corpus data may contain sensitive personal information (e.g. video, audio) and speakers may not consent to making it public.
This is explicitly addressed already re:sociolinguistic interviews (in fact, in more detail than the reviewer considers...)

> Authors of the study may not have the rights to publish the data that their study is based. In this case, it may be possible to make processed data publicly available, but not the raw data (i.e. data can mean different things, and should be distinguished in more detail here).
This sort of situation is kind of addressed: "In more uncommon cases in which institutional policies do not permit the sharing of derived data sets, synthetic data containing the same statistical properties can be generated and shared freely (See Quintana, 2020)." Is the situation the reviewer described common enough to be worth mentioning when this solution to a similar issue is already offered?

> it may simply be the fear of making all data and annotation choices criticiseable by making everything publicly available.
Maybe after the paragraph starting "A substantial hurdle that cannot be overlooked revolves..." we can possible add something along the lines of:

"Among researchers, there can exist anxieties unrelated to technical considerations about sharing data [@stieglitz2020researchers]. @stieglitz2020researchers, in a study investigating 995 researchers from 13 universities in Germany across various fields, found that there were anxieties about competitive pressures, such as losing the opportunity to publish again from the same dataset before another researcher does. In this case, anxieties can be quelled with the knowledge that the data can be made available after all research inquiries by the original researchers have been completed."

We can also add something along these lines, but I can't find any papers that talk on this topic: "Furthermore, researchers may have anxieties about opening themselves up to criticism by making their data publicly available. Although this is a possibiltity, the peer review process is a common and familiar process in the sciences. Analyses that are not coherent with the archived data should be highlighted as early in the peer review process as possible. Open data practices allow for this to take place and gives researchers the opportunity to review their data and corresponding analyses."

citation: 
@article{stieglitz2020researchers,
  title={When are researchers willing to share their data?--Impacts of values and uncertainty on open data in academia},
  author={Stieglitz, Stefan and Wilms, Konstantin and Mirbabaie, Milad and Hofeditz, Lennart and Brenger, Bela and L{\'o}pez, Ania and Rehwald, Stephanie},
  journal={PLoS one},
  volume={15},
  number={7},
  pages={e0234172},
  year={2020},
  publisher={Public Library of Science San Francisco, CA USA}
}

**Comment by jvcasillas** [comment]
Addressed via https://github.com/RAP-group/guide_to_open_science/commit/062346181c48cd88af992880c45800b5154601ae
