### ISSUE TITLE
R2: open data, accessibility to underrepresented communities

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#38]
> - “Making linguistic data accessible to all researchers promotes participation in and with underrepresented communities. Furthermore, it can increase the study of diverse and underreported languages, which fosters a more inclusive and comprehensive understanding of the global linguistic landscape.”
--> Please explain why and how accessible linguistic data promotes the researchers’ participation with the (potentially underrepresented) speaker communities? While I am sympathetic to this argument, it needs to be spelled out more and made more concrete in order to be meaningful.

TODO

- [ ] spell it out for R2 (2ish sentences)

**Comment by IvanAndreuRascon** [comment]
???? -hbu this? 
Making linguistic data accessible to all researchers beneficts specially underrepresented communities, as other researchers can access data that would not normally be accessible, fosterin in an indirect way more inclusive and comprehensive understanding of the global linguistic landscape.

**Comment by jvcasillas** [comment]
Addressed via https://github.com/RAP-group/guide_to_open_science/commit/3ba7e8499cc3bc59d99c58079fb86d50143dbd4b
