### ISSUE TITLE
R2: open data, move/restructure

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#40]
> - “The privacy and consent of participants must be safeguarded...”
--> OK, this is the kind of information that I was waiting for earlier; consider moving this paragraph up. Also, not all linguistic studies face ethical issues: What about studies that work with databases / corpora that have been compiled by third parties, which are publicly accessible and which the authors simply use as is. They are far removed from any speakers in this case and had no influence on any decision of data collection and processing that went into compiling the database. Or what about historical linguistics? The role that participants or informants play in different types of linguistic studies deserves a more fine-grained discussion.

TODO

- [x] See if there is a good place to move to
- [x] Regarding "not all linguistic studies bla blah"... yeah we know.. we aren't talking about those ones (add sentence clarifying that what we are saying doesn't apply to every single subfield... (check to see if this point has already been made)

**Comment by IvanAndreuRascon** [comment]
While open data offers significant benefits, the field of linguistics faces unique ethical challenges that complicate its implementation. Linguistic data often includes personal information that is difficult to anonymize—especially in audio and video recordings—making the safeguarding of participant privacy and the obtaining of informed consent crucial. However, not all linguistic studies are constrained by these concerns. Research that utilizes third-party databases or corpora, focuses on historical linguistics, or employs artificial intelligence language models without direct participant interaction may not encounter these issues.

**Comment by jvcasillas** [comment]
Addressed via many other issues https://github.com/RAP-group/guide_to_open_science/pull/64
