### ISSUE TITLE
R2: open data, add prolific link

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#43]
> - Prolific --> add a link, e.g. in a footnote.

TODO 

- [ ] add link

**Comment by RobertEspo** [comment]
https://www.prolific.com/
Prolific. (n.d.). Participant recruitment for surveys and research. https://www.prolific.com/

Do they literally mean just this?

**Comment by jvcasillas** [comment]
Link added via https://github.com/RAP-group/guide_to_open_science/commit/782cf98349bdbfcccef339b51a1f5f9da26f8eb4
