### ISSUE TITLE
R2: open data, synthetic data sets

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#44]
> - “In more uncommon cases in which institutional policies do not permit the sharing of
derived data sets, synthetic data containing the same statistical properties can be generated and shared freely (See Quintana, 2020).”
--> Please elaborate how this would work.

TODO

- [x] Add example in Supp. materials
- [x] Ref supp. materials in text at this point

**Comment by IvanAndreuRascon** [comment]
Si se decide hacer.. posible info.. 

Steps to follow 
1.	Analyze the original model 
Obtain original distributions, correlations, variances, and other statistical metrics. regression lines, clusteing, etc. 
2.	Create a generative model
o	With the previous information create models like multivariate normal distributions, copulas, or Bayesian networks that recreate as close as possible the original information. Possibility of using (Generative Adversarial Networks (GANs) or Variational Autoencoders (VAEs))
3.	Generate synthetic:
Drawing samples from the developed model to create new data points with identical data points
4.	Validate the Synthetic Data:
Reanalyze mans, standard deviations, including the use of plots, to see that are visually similar and re run the analysis to check that the data offers identical data.

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/d23bb6bee51317b50f04377f6d978f1849a349ac
