### ISSUE TITLE
R2: open data, add table?

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#46]
> - “Free repositories designed for the purpose of sharing research materials, such as the Open Science Framework (Foster & Deardorff, 2017), github, etc., are preferable and can be accessed simply by sharing a link.”
--> Here, it would actually be helpful to spell this out a bit more and mention e.g. zenodo as another option. For readers less familiar with these options, it would be valuable to add a table with different platforms / systems and provide information about long-term support, version control, possibility of DOI, anonymous links (e.g. what OSF offers and what is very
useful for sharing data and code during the revision stage of a study), etc.

TODO

- [x] Decide if we want to make this table
- [x] If yes, compile info and add

**Comment by IvanAndreuRascon** [comment]
Si se decide hacer...

**Open Science Framework (OSF):**
Long-term support
Version control
DOI assignment
Allows anonymous sharing
There is project management and collaboration

**GitHub:**
Long-term support
Version control
Integrates with Zenodo for DOI assignment
Public repositories can be shared anonymously
Mostly for coding 

**Zenodo:**
Long-term support
Preserves version history (can also be linked with github)
Assigns DOIs automatically
Allows anonymous sharing
Very polyvalent 

**Figshare:**
Long-term support
Limited version control
DOI assignment
Allows anonymous sharing
Good for sharing datasets and figures

**Comment by jvcasillas** [comment]
gitlab
bitbucket

possibly contrast with poorer versions/choices of the same thing (box, google drive)

**Comment by IvanAndreuRascon** [comment]
Asi? 


| Platform                     | Long-term Support | Version Control             | DOI Assignment         | Anonymous Sharing          | Key Features                                   |
|------------------------------|-------------------|-----------------------------|------------------------|----------------------------|-----------------------------------------------|
| Open Science Framework (OSF) | ✅               | ✅                         | ✅                    | ✅                        | Project management and collaboration          |
| GitHub                       | ✅               | ✅                         | Integrates with Zenodo | ✅ (public repositories)   | Mostly for coding                              |
| Zenodo                       | ✅               | ✅ (via GitHub integration) | ✅                    | ✅                        | Very polyvalent                                |
| Figshare                     | ✅               | Limited                    | ✅                    | ✅                        | Good for sharing datasets and figures         |
| GitLab                       | ✅               | ✅                         | Integrates with Zenodo | Limited                   | Primarily for coding and DevOps               |
| Bitbucket                    | ✅               | ✅                         | Integrates with Zenodo | Limited                   | Primarily for coding and DevOps               |
| Box                          | ❌               | ❌                         | ❌                    | Limited                   | Basic file storage and sharing                |
| Google Drive                 | ❌               | ❌                         | ❌                    | Limited                   | Convenient for personal file sharing          |

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/dd0637d9437bc5a972548cc364364d421b81b037
