### ISSUE TITLE
R2: open data, mention field-specific challenges

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#47]
> - “While linguistics does face legitimate, field-specific challenges, ultimately the benefits of
open data outnumber these challenges, and researchers should take the stance to share what is ethically reasonable.”
--> My impression when reading this is that the only field-specific challenge mentioned was the point on sensitive speaker data. I generally agree with the statement, but in order to make this statement at the end of the section, the section would need to be much more explicit about the different challenges taking into account the different areas of linguistics.
>
> - Another point to consider is the following, although it may not immediately relate to data and more to the inclusion of lesser studied languages and integration of speaker communities in linguistic research: There are linguistic journals that allow / require an additional abstract of the papers in the target language or another local language besides the usual abstract in English. From personal experience, I know that Linguistics Vanguard offers this as an option (although I am not sure if you can find this information other than submitting a paper). Another journal that makes use of this practice is the Journal of African Languages and Linguistics (just to give some examples from the most recent volume: https://www.degruyter.com/document/doi/10.1515/jall-2023-2008/html, https://www.degruyter.com/document/doi/10.1515/jall-2023-2011/html)

TODO 

- [ ] brainstorm a few more examples in other areas and incorporate them into the section 
- [ ] Not sure what R2 wants us to do with that second paragraph

**Comment by RobertEspo** [comment]
For example, a neurolinguistic study investigating event related potentials (ERPs) could share their raw data for transparency, as well as preprocessed data with the code used to transform the raw data and a corresponding description for facilitation of reanalysis. In another field, the creation of a corpus will benefit from open access and the use of standardized file formats; the analysis of a corpus will benefit from sharing the search queries, the analysis code, and a description of the analysis code.

^ These examples could potentially go before "At the heart of these challenges are ethical concerns".

**Comment by RobertEspo** [comment]
"Making linguistic data freely available improves credibility in our findings, to other researchers and the general public. Prohibiting or impeding access to data collected for publicly funded research is unethical and a detriment to inclusivity."

After ^ this paragraph, we could potentially add the following:

Furthermore, some journals, such as the Journal of African Languages and Linguistics, requires that the abstract be translated to the target language, allowing for greater access to the general public, as well as non-English speaking researchers.

Kind of sketchy, though, not sure if this is really a valid claim.

**Comment by jvcasillas** [comment]
Included two examples via https://github.com/RAP-group/guide_to_open_science/commit/88dfe07202916021159abe4bf1106c28ec6d6973
