### ISSUE TITLE
R2: reproducibility, "is crucial" - rephrase

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#48]
> - “As we have seen, reproducibility is now a crucial aspect of any scientific study.”
--> Where did we see that? Also, I agree that it should be, but reproducibility is not yet a crucial aspect of any scientific study, unfortunately. Please rephrase.

TODO

- [x] I assume we referred to the reproducibility crisis prior, but reread and consider how to rephrase

**Comment by RobertEspo** [comment]
Having seen the consequences from the reproducibility crisis in other fields, reproducibility must be a crucial aspect of any scientific study.

^ Is this what the original sentence is getting at? An exhortation, not a fact?

**Comment by jvcasillas** [comment]
Rewritten in https://github.com/RAP-group/guide_to_open_science/commit/6965b4e401acc3c7a6a9c2f037a062113f722d51
