### ISSUE TITLE
R2: reproducibility, at worst

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#49]
> - “At worst, a lack of reproducibility can lead to irreproducible results and wasted resources.” --> Is this really the worst consequence? Is it not worse (or equally bad) that we may end up with results that are taken as a given for decades in a given linguistic field, because the original study was not reproducible and never replicated but influential for some reason?

TODO

- [ ] Fine (nitpicky). Reframe as a possible undesirable outcome (though maybe not the worst)

**Comment by RobertEspo** [comment]
I edited the paragraph a bit, but didn't change any of the ideas:

In general, reproducibility helps to increase the credibility of research findings and allows other researchers to verify and build on existing work. A lack of reproducibility can lead to irreproducible results and wasted resources, having serious implications for public health and policy decisions based on research findings. It is necessary to be transparent about the methods used in research to ensure reproducibility, which includes not only the data collection and analysis methods, but also the code used to conduct the analysis.

**Comment by jvcasillas** [comment]
Change included in https://github.com/RAP-group/guide_to_open_science/commit/9c663033978983b64ed71315b7c1852ce0fc2d87
