### ISSUE TITLE
R2: reproducibility, implications for public health and policy

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#50]
> - “This can have serious implications for public health and policy decisions based on research findings.”
--> Is this statement about linguistics or research in general? Please clarify.

TODO

- [x] I think this was about research in general. Clarify (remove?)

**Comment by mfeliuribas** [comment]
I didn't write this part, so I am not sure what the writer had in mind (although it seems a statement about research in general). We could either remove it (as suggested by Joseph) or adapt it to linguistics by saying something like "At worst, a lack of reproducibility can lead to irreproducible results and wasted resources. This could hinder advancements in linguistic theory and theories of language acquisition, and could have serious implications for education and language policy decisions based on research findings".

**Comment by jvcasillas** [comment]
Revamped via https://github.com/RAP-group/guide_to_open_science/commit/b8dc4a7a80ebb6f27c379ac995e8c3d7b3126236
