### ISSUE TITLE
R2: reproducibility, avoid repetition

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#51]
> - “In linguistics there is increasing awareness of the importance of reproducibility, and many
researchers are beginning to take steps to improve the reproducibility of their research.”
--> too many reproducibilities in one sentence, rephrase.

TODO

- [ ] agreed. rephrase

**Comment by RobertEspo** [comment]
Researchers in linguistics are becoming increasingly aware of the importance of reproducibility and are beginning to take steps to improve it in their own research.

**Comment by jvcasillas** [comment]
Addressed in https://github.com/RAP-group/guide_to_open_science/commit/b8dc4a7a80ebb6f27c379ac995e8c3d7b3126236
