### ISSUE TITLE
R2: preregistration, experimental research

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#55]
> - “Researchers face vital decisions while engaging in research, with inherent flexibility involved in the process of designing and conducting experiments, as well as analyzing the results (Simmons, Nelson, & Simonsohn, 2011).”
--> Does this mean you only consider experimental linguistics research? This needs to be framed differently, or, the scope of the paper should be reduced to experimental linguistics.

TODO

- [x] replace "experiments" with "projects"

**Comment by stephanierod** [comment]
“Researchers face vital decisions while engaging in research, with inherent flexibility involved in the process of designing and conducting projects, as well as analyzing the results (Simmons, Nelson, & Simonsohn, 2011).”

**Comment by jvcasillas** [comment]
Revised via https://github.com/RAP-group/guide_to_open_science/commit/4992c29badfc4db45df7e27537fa9861725bca02
