### ISSUE TITLE
R2: preregistration, Explain coretta et al

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#56]
> - Coretta et al. 2023: Please explain in a few sentences what the study did and what it showed; it is impossible to understand (and appreciate) that without knowing the study.

TODO

- [x] figure out where the particular citation R2 is referring is and describe study (it's the MSA study)

**Comment by GaboSJW** [comment]
This type of flexibility, referred to as "researcher degrees of freedom," can significantly impact quantitative research, particularly in fields like linguistics. For instance Coretta et al. (2023) conducted a study providing the same speech-production data set to 46 research teams with the task to answer the same research question. Their findings revealed substantial variability in the reported effect sizes and their interpretations. Furthermore, using Bayesian meta-analytic tools, they showed that this variability could not be explained by analysts' prior beliefs, expertise, or the perceived quality of their analyses.

**Comment by jvcasillas** [comment]
Added via https://github.com/RAP-group/guide_to_open_science/commit/f3ae6d212a84103cf4e1f463af5a8a74e5b9eb6b
