### ISSUE TITLE
R2: preprints, example preprint servers

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#59]
> - “First, select a pre-print server that aligns with the course of research.”
--> Please give examples of suitable pre-print servers for different linguistic areas. Again, a table would be very helpful.

- [ ] Get list of servers, consider making a table

**Comment by jvcasillas** [comment]
No table (for now), get short-ish list of ling-related servers and add to parenthesis

**Comment by jvcasillas** [comment]
This is for Eva

**Comment by jvcasillas** [comment]
@ecorregidor here is a starting point (chatGPT generated so we need to check links, etc.):

| Server                 | Discipline(s)                           | URL                                   |
|------------------------|------------------------------------------|---------------------------------------|
| arXiv                 | Physics, mathematics, computer science, quantitative biology, quantitative finance, statistics | [arXiv](https://arxiv.org/)          |
| bioRxiv               | Biology and life sciences               | [bioRxiv](https://www.biorxiv.org/)  |
| medRxiv               | Health sciences and medicine            | [medRxiv](https://www.medrxiv.org/)  |
| SSRN                  | Social sciences, humanities, legal studies | [SSRN](https://www.ssrn.com/)       |
| OSF Preprints         | Multidisciplinary                       | [OSF Preprints](https://osf.io/preprints/) |
| Zenodo                | Broad disciplines                       | [Zenodo](https://zenodo.org/)        |
| ChemRxiv              | Chemistry                               | [ChemRxiv](https://chemrxiv.org/)    |
| PsyArXiv              | Psychology                              | [PsyArXiv](https://psyarxiv.com/)    |
| EarthArXiv            | Earth sciences                          | [EarthArXiv](https://eartharxiv.org/) |
| EconStor              | Economics                               | [EconStor](https://www.econstor.eu/) |
| RePEc                 | Economics                               | [RePEc](https://repec.org/)          |
| SocArXiv              | Sociology and social sciences           | [SocArXiv](https://osf.io/preprints/socarxiv/) |
| HAL                   | French-language research                | [HAL](https://hal.archives-ouvertes.fr/) |
| SciELO Preprints      | Latin American and Iberian Peninsula research | [SciELO Preprints](https://preprints.scielo.org/) |
| IndiaRxiv             | Indian research                         | [IndiaRxiv](https://indiarxiv.org/)  |
| Preprints.org         | Open access, multidisciplinary          | [Preprints.org](https://www.preprints.org/) |
| F1000Research         | Open science with post-publication peer review | [F1000Research](https://f1000research.com/) |

**Comment by ecorregidor** [comment]
"First, select a pre-print server that aligns with the course of research (options are abundant: LingBuzz or PsyArXiv for general linguistics; arXiv and ACL Anthology Preprints for computational linguistics; EdArXiv for Education and Applied Linguistics; CogPrints for Cognitive Science and Linguistics; language-specific linguistic servers are also available, such as HAL Archives Ouvertes for French)"

I've done a quick research, but I am not confident about their size. The number of papers uploaded to some servers is not really big. I have a longer list if we need to change some of them.

Division by areas in linguistics seemed like a good idea!

**Comment by jvcasillas** [comment]
consider adding column for database size

**Comment by jvcasillas** [comment]
add column for year created (the server)

**Comment by ecorregidor** [comment]
New table here: https://docs.google.com/document/d/1G2d5P4esMMJQoBjNLSeXGFS8IBBvXKxOEQyu3amN-p8/edit?usp=sharing

**Comment by jvcasillas** [comment]
converted to csv and added via https://github.com/RAP-group/guide_to_open_science/commit/fb6f5563c95e63c6192aaa6e9b9f97479ce1ecb7
