### ISSUE TITLE
R2: references

### ISSUE THREAD

**Issue by jvcasillas** [RAP-group/guide_to_open_science#61]
> - Some references contain incomplete author lists 
--> all authors should be cited.

TODO

- [x] examine refs, see if we can figure out what they are referring to

**Comment by mfeliuribas** [comment]
Could the reviewer be referring to the articles that have many, many authors? I just checked the refs and, for example, in Bochynska et al. (2023) the list of authors is not complete, as some authors are replaced by "..." 

> Bochynska, A., Keeble, L., Halfacre, C., Casillas, J. V., Champagne, I.-A., Chen, K., … Roettger, T. B. (2023). Reproducible research practices and transparency across linguistics. Glossa Psycholinguistics, 2(1, 18), 1–36. https://doi.org/10.5070/G6011239

This also applies to other refs, some of which use "..." and, others, "et al.others".
> Camerer, C. F., Dreber, A., Holzmeister, F., Ho, T.-H., Huber, J., Johannesson, M., et al.others. (2018). Evaluating the replicability of social science experiments in nature and science between 2010 and 2015. Nature Human Behaviour, 2(9), 637–644. https://doi.org/10.1038/s41562-018-0399-z


<br>

Also, some of the links/dois are not working:
- Berger, R. (2015) 
- Camerer et al. (2016)
- FORRT (2021)

**Comment by mfeliuribas** [comment]
P.S. I think that someone should check it too, just in case...

**Comment by jvcasillas** [comment]
DOIs and links fixed via https://github.com/RAP-group/guide_to_open_science/commit/e35ae1cf4463eb02ee5b47a7cd72877a3291dc9b
